### ISSUE TITLE
Use event-based model completely

### ISSUE THREAD

**Issue by shuwens** [lkatalin/Categorization#4]
We want to both have `A.start` and `A.stop` in the DAG

**Comment by lkatalin** [comment]
Contemplating what "concurrency" means in a model where two nodes cannot be concurrent because each node represents one instant in time, never overlapping with another node.

**Comment by shuwens** [comment]
@lkatalin I think this issue is what you want to address while refactoring the code. Feel free to pull me in if you want to start the refactoring

**Comment by lkatalin** [comment]
Please ignore the above!

**Comment by lkatalin** [comment]
FYI made progress working on this. Works for the simplest case right now:

![simple](https://user-images.githubusercontent.com/22075926/32384853-9e61fbd6-c092-11e7-8731-44056a1024e0.png)

**Comment by lkatalin** [comment]
Seems to be working for cases with children. Next I will test it on cases with concurrency.

![works_with_child_nodes](https://user-images.githubusercontent.com/22075926/32571165-7db02e34-c494-11e7-8a0d-c1664972f91b.png)

**Comment by lkatalin** [comment]
- [x] Works on simple case with no children
- [x] Works on cases with children
- [x] Works on cases with concurrency / synch points
- [x] Works on cases with concurrency and children

**Comment by lkatalin** [comment]
Some good results here with concurrency. I will test on a few more examples before closing the issue, but here it works:

![success](https://user-images.githubusercontent.com/22075926/32916044-d8c5d99a-cae8-11e7-8610-f98c3e33f0d3.png)

Ask me if you want to see the JSON this came from (Github won't support it as an attachment).

**Comment by lkatalin** [comment]
Closing as the model seems to be working.
