### ISSUE TITLE
Have DFT in processing use labels instead of trace_ids

### ISSUE THREAD

**Issue by lkatalin** [lkatalin/Categorization#7]
@shwsun 

Currently we feed a .dot file of the format `trace_id -> trace_id [label="(component)"]` into the Categorizer. The Categorizer turns each node of the .dot file into a [Node object](https://github.com/lkatalin/Categorization/blob/master/make_nodes.py) and [establishes relationships](https://github.com/lkatalin/Categorization/blob/master/make_dag.py) between Node objects based on the .dot edges to turn them into a tree/DAG. Then it does a [depth first traversal](https://github.com/lkatalin/Categorization/blob/master/group_traces.py) of each tree/DAG to extract a hash value representing the tree/DAG structure. When these hash values are the same, two traces are [put in the same group](https://github.com/lkatalin/Categorization/blob/master/group_traces.py) for analysis.

Because the [depth first traversal](https://github.com/lkatalin/Categorization/blob/master/group_traces.py) uses `cur_node.id` to build up the hash value, and the Node's id comes from the trace_id, the hash values are based on trace_ids. 

We will need to make one of these two changes: 1) change the Node id to use the .dot label instead of the .dot trace_id in `make_dag.py` or 2) change the [depth first traversal](https://github.com/lkatalin/Categorization/blob/master/group_traces.py) to use `cur_node.name` (or some similar field which stores the label in `make_dag.py`) to create the hash value that will be used for grouping. I think (2) makes more sense, that way we can preserve the trace_ids in the Nodes.

**Comment by shuwens** [comment]
@lkatalin Do you think I can work on this right away or I should wait til you get the refactoring part done?

**Comment by lkatalin** [comment]
I think actually changing this part should be fine regardless of the refactoring. Refactoring will change what values go into things like Node.id and how many nodes there are, but you wouldn't see that difference by switching the value used in DFT.

Please do make a new branch!

**Comment by shuwens** [comment]
@lkatalin I think I fixed it. Please take a look at the pull request
